version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: my-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: insignia-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_USER=rootuser
      - MONGO_PASS=rootpass
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=insignia-nodejs
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    # command: npm run start
    command: npm run dev

volumes:
  mongo-data:
