apiVersion: apps/v1
kind: Deployment
metadata:
  name: insignia-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insignia-app
  template:
    metadata:
      labels:
        app: insignia-app
    spec:
      containers:
        - name: insignia-app
          image: ninoloid/insignia-app:latest
          ports:
            - containerPort: 3000
